version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./:/app
    working_dir: /app
    command: npm run dev -- --mode production
    ports:
      - "5173:5173"
    restart: on-failure
    environment:
      - NODE_ENV=production
