functions:
  - name: get_product_pages
    description: |
      This function finds products that match the user's query, utilizing product descriptions as a proxy to suggest options. Not all products found may be the best fit for the user.
    parameters:
      type: object
      properties:
        name_of_product:
          type: string
          description: The name of the product. If not specified by the user, set to null.
        type_of_product:
          type: string
          description: The type or category of the product requested by the user (e.g., laptops, smartphones, accessories).
        brand_requested:
          type: array
          description: The array of brands that the user is interested in. If not specified, set to [null].
          items:
            type: string
        screen_size:
          type: string
          description: The screen size of the product requested by the user. If not specified, set to [null].
        specs:
          type: object
          description: The specifications of the product requested by the user. If not specified, set to null, if any one of the properties is not provided, set that to null.
          properties:
            processor:
              type: string
            ram:
              type: string
            storage:
              type: string
        price:
          type: string
          description: The price range of the product requested by the user. If not specified, set to null.
        other_information:
          type: string
          description: Any additional information provided by the user that could assist in finding the best matching products. If no information is provided, set to null.
        quantity:
          type: integer
          description: The number of product pages to search to serve the user. Default is 1, but may be adjusted based on the breadth of the user's request.
    required: [name_of_product, type_of_product, brand_requested, other_information, quantity]
    allow: true

  - name: open_product_page
    description: |
      This function opens the page of a given product. Confirm with the user before calling this function.
    parameters:
      type: object
      properties:
        product_uuid:
          type: string
          description: The unique identifier of the product page retrieved from the get_product_pages function.
    required: [product_uuid]
    allow: true

  - name: close_product_page
    description: |
      This function closes the page of a product and returns to the main page displaying all products. It can only be called if a product page is already open.
    parameters:
      type: object
      properties: {}
    allow: false

  - name: get_user_actions
    description: |
      This function returns the list of the latest 10 user actions, providing insight into the current state of the interface.
    parameters:
      type: object
      properties: {}
    allow: false

  - name: add_product_to_cart
    description: |
      This function adds a product to the user's shopping cart. It should only be called with the necessary information of the product UUID and quantity.
    parameters:
      type: object
      properties:
        product_uuid:
          type: string
          description: The unique identifier of the product.
        quantity:
          type: integer
          description: The quantity of the product to be added to the cart.
    required: [product_uuid, quantity]
    allow: true

  - name: remove_product_from_cart
    description: |
      This function removes a product from the user's shopping cart. It should only be called with the necessary information of the product UUID.
    parameters:
      type: object
      properties:
        product_uuid:
          type: string
          description: The unique identifier of the product to be removed from the cart.
    required: [product_uuid]
    allow: true

  - name: open_shopping_cart
    description: |
      This function opens the user's shopping cart to view its contents.
    parameters:
      type: object
      properties: {}
    allow: true

  - name: close_shopping_cart
    description: |
      This function closes the user's shopping cart.
    parameters:
      type: object
      properties: {}
    allow: true

  - name: place_order
    description: |
      This function places an order with the items currently in the user's shopping cart.
    parameters:
      type: object
      properties: {}
    allow: true

  - name: activate_handsfree
    description: |
      This function activates a hands-free chat experience where responses are provided via voice to the user interface.
    parameters:
      type: object
      properties: {}
    allow: false
